// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Dice20Controller from "./dice20_controller"
application.register("dice20", Dice20Controller)

import StoryController from "./story_controller"
application.register("story", StoryController)
